### PR TITLE
feature suspend job

### PR DESCRIPTION
**Pull request by YasuhiroKinoshita**
## feature
Implements suspend cron job.

## why
Sometime i want to suspend cron job and resume it.(delete it and add new job each time is not useful when i want to add exactly same job)

### CODE REVIEW

**Comment by june29** [comment]
:+1:

**Comment by YasuhiroKinoshita** [comment]
@r7kamura check this plz

**Comment by r7kamura** [comment]
@YasuhiroKinoshita Oh, I'm sorry I missed this PR. I'll check this now :pray:

**Comment by r7kamura** [comment]
Merged with [some modifications](https://github.com/r7kamura/ruboty-cron/compare/3399c70b7a96183b397df8e8b70a42b2df510641...9fae9940eb9932e1d576d60e22e0850e7b6ee003) and just released v1.1.0 :+1:

**Comment by june29** [comment]
@YasuhiroKinoshita @r7kamura Thank you for coding and release! I'll use this feature :blush:

**Comment by YasuhiroKinoshita** [comment]
Thanks!!

＼＼\\(۶•̀ᴗ•́)۶//／／

**Pull request merged**
